language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - hhvm
  - hhvm-nightly
before_install:
  - composer self-update
  - composer install
script:
  - composer test
after_script:
  - composer coveralls
matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm-nightly
