language: php
php:
  - 5.6
  - 5.5
  - hhvm
before_install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source
script:
  - composer test
after_script:
  - composer coveralls
matrix:
  fast_finish: true
sudo: false
